/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and project-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}

// ProjectNamespaceListerExpansion allows custom methods to be added to
// ProjectNamespaceLister.
type ProjectNamespaceListerExpansion interface{}
