/*
SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and project-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corecssapcomv1alpha1 "github.com/sap/project-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ProjectLister helps list Projects.
// All objects returned here must be treated as read-only.
type ProjectLister interface {
	// List lists all Projects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corecssapcomv1alpha1.Project, err error)
	// Projects returns an object that can list and get Projects.
	Projects(namespace string) ProjectNamespaceLister
	ProjectListerExpansion
}

// projectLister implements the ProjectLister interface.
type projectLister struct {
	listers.ResourceIndexer[*corecssapcomv1alpha1.Project]
}

// NewProjectLister returns a new ProjectLister.
func NewProjectLister(indexer cache.Indexer) ProjectLister {
	return &projectLister{listers.New[*corecssapcomv1alpha1.Project](indexer, corecssapcomv1alpha1.Resource("project"))}
}

// Projects returns an object that can list and get Projects.
func (s *projectLister) Projects(namespace string) ProjectNamespaceLister {
	return projectNamespaceLister{listers.NewNamespaced[*corecssapcomv1alpha1.Project](s.ResourceIndexer, namespace)}
}

// ProjectNamespaceLister helps list and get Projects.
// All objects returned here must be treated as read-only.
type ProjectNamespaceLister interface {
	// List lists all Projects in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corecssapcomv1alpha1.Project, err error)
	// Get retrieves the Project from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corecssapcomv1alpha1.Project, error)
	ProjectNamespaceListerExpansion
}

// projectNamespaceLister implements the ProjectNamespaceLister
// interface.
type projectNamespaceLister struct {
	listers.ResourceIndexer[*corecssapcomv1alpha1.Project]
}
