/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and project-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/project-operator/api/v1alpha1"
	corecssapcomv1alpha1 "github.com/sap/project-operator/pkg/client/clientset/versioned/typed/core.cs.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeProjects implements ProjectInterface
type fakeProjects struct {
	*gentype.FakeClientWithList[*v1alpha1.Project, *v1alpha1.ProjectList]
	Fake *FakeCoreV1alpha1
}

func newFakeProjects(fake *FakeCoreV1alpha1, namespace string) corecssapcomv1alpha1.ProjectInterface {
	return &fakeProjects{
		gentype.NewFakeClientWithList[*v1alpha1.Project, *v1alpha1.ProjectList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("projects"),
			v1alpha1.SchemeGroupVersion.WithKind("Project"),
			func() *v1alpha1.Project { return &v1alpha1.Project{} },
			func() *v1alpha1.ProjectList { return &v1alpha1.ProjectList{} },
			func(dst, src *v1alpha1.ProjectList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ProjectList) []*v1alpha1.Project { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ProjectList, items []*v1alpha1.Project) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
