name: Publish Custom Resource Definitions

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  WORKFLOW_USER_NAME: ERP4SME-DevOps-GitHub-Workflow-User
  WORKFLOW_USER_EMAIL: 134080766+ERP4SME-DevOps-GitHub-Workflow-User@users.noreply.github.com

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Setup regctl
      run: |
        curl -sSf -L -o $RUNNER_TEMP/regctl https://github.com/regclient/regclient/releases/download/v0.4.8/regctl-linux-amd64
        chmod a+x $RUNNER_TEMP/regctl

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the registry
      run: |
        $RUNNER_TEMP/regctl registry login $REGISTRY --user ${{ github.actor }} --pass-stdin <<< ${{ secrets.GITHUB_TOKEN }}

    - name: Build artifact
      run: |
        cd crds
        repository=${{ github.repository }}/crds
        tar cvz * | $RUNNER_TEMP/regctl artifact put -m application/gzip $REGISTRY/${repository,,}:${{ github.event.release.tag_name }}

  update-chart:
    runs-on: ubuntu-22.04
    env:
      CHART_REPOSITORY: ${{ github.repository }}-helm
      CHART_DIRECTORY: chart

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout chart repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.CHART_REPOSITORY }}
        path: chart-repository
        token: ${{ secrets.WORKFLOW_USER_GH_TOKEN }}

    - name: Update chart repository
      run: |
        cd chart-repository
        old_version=$(yq .appVersion $CHART_DIRECTORY/Chart.yaml)
        old_semver=${old_version#v}
        new_version=${{ github.event.release.tag_name }}
        new_semver=${new_version#v}

        higher_semver=$(echo -e "$old_semver\n$new_semver" | sort -r -n -t. -k1 -k2 -k3 | head -n1)
        if [ "$higher_semver" != "$new_semver" ]; then
          echo "Target appVersion ($new_version) is lower than current appVersion ($old_version); skipping update."
          exit 0
        fi

        echo "Updating custom resource definitions ($CHART_DIRECTORY/crds) ..."
        rm -rf $CHART_DIRECTORY/crds
        cp -r ../crds $CHART_DIRECTORY

        echo "Updating appVersion in $CHART_DIRECTORY/Chart.yaml (current: $old_version; target: $new_version) ..."
        perl -pi -e "s#^appVersion:.*#appVersion: $new_version#g" $CHART_DIRECTORY/Chart.yaml

        if [ -z "$(git status --porcelain)" ]; then
          echo "Nothing has changed; skipping update."
          exit 0
        fi

        git config user.name "$WORKFLOW_USER_NAME"
        git config user.email "$WORKFLOW_USER_EMAIL"
        git add -A
        git commit -F- <<END
        Update chart (triggered by operator release $new_version)
        Repository: ${{ github.repository }}
        Release: ${{ github.event.release.tag_name }}
        Commit: ${{ github.sha }}"
        END
        git push